cache:
  paths:
  - apt-cache/

before_script:
  - apt-get -y update
  - apt-get -y install unzip

pages:
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  - wget -O html.zip https://gitlab.com/nieper/thunder/-/jobs/artifacts/nieper/download?job=html
  - unzip -j html.zip "doc/thunder.html/*.html" -d public/manual/html_node 
  artifacts:
    paths:
    - public
  only:
  - pages
