variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get -y update
  - apt-get -y install texinfo libgmp-dev libmpfr-dev libmpc-dev
  - ./bootstrap
  - ./configure

check:
  script:
    - make check
