before_script:
  - apt-get -y update
  - apt-get -y install texinfo libgmp-dev libmpfr-dev libmpc-dev
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - ./bootstrap
  - ./configure

check:
  script:
    - make check
